//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_vjp_pr0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDThanhToan
    {
        public string MaCTHDThanhToan { get; set; }
        public string MaHD { get; set; }
        public string MaHang { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HDThanhToan HDThanhToan { get; set; }
        public virtual ThongTinHang ThongTinHang { get; set; }
    }
}
