//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_vjp_pr0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDNhap()
        {
            this.CTHDNhaps = new HashSet<CTHDNhap>();
        }
    
        public string MaHDNhap { get; set; }
        public string MaThuongHieu { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string GhiChu { get; set; }
        public string MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDNhap> CTHDNhaps { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
