//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_vjp_pr0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLQAoEntities : DbContext
    {
        public QLQAoEntities()
            : base("name=QLQAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acount> Acounts { get; set; }
        public virtual DbSet<CTHDNhap> CTHDNhaps { get; set; }
        public virtual DbSet<CTHDThanhToan> CTHDThanhToans { get; set; }
        public virtual DbSet<HDNhap> HDNhaps { get; set; }
        public virtual DbSet<HDThanhToan> HDThanhToans { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongTinHang> ThongTinHangs { get; set; }
        public virtual DbSet<ThongTinKH> ThongTinKHs { get; set; }
        public virtual DbSet<ThuongHieu> ThuongHieux { get; set; }
    }
}
