//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_vjp_pr0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinHang()
        {
            this.CTHDNhaps = new HashSet<CTHDNhap>();
            this.CTHDThanhToans = new HashSet<CTHDThanhToan>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaLoaiHang { get; set; }
        public string MaSize { get; set; }
        public Nullable<double> DonGia { get; set; }
        public string MaThuongHieu { get; set; }
        public string Anh { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDNhap> CTHDNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDThanhToan> CTHDThanhToans { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
        public virtual Size Size { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
